#!/usr/bin/env python3
"""Generate TypeScript declarations from the FastAPI OpenAPI schema.

This intentionally handles the OpenAPI subset emitted by the local Pydantic
schemas. It avoids an npm-side generator dependency and keeps contract output
stable enough for drift checks.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Any

from app.main import app

IDENTIFIER_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")
NULL_SCHEMA = {"type": "null"}


def _schema_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _literal(value: Any) -> str:
    if isinstance(value, str):
        return repr(value)
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _prop(name: str) -> str:
    if IDENTIFIER_RE.match(name):
        return name
    return repr(name)


def _dedupe(parts: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for part in parts:
        if part not in seen:
            out.append(part)
            seen.add(part)
    return out


def _ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _schema_name(schema["$ref"])

    const = schema.get("const")
    if const is not None:
        return _literal(const)

    enum = schema.get("enum")
    if enum:
        return " | ".join(_literal(item) for item in enum)

    for key in ("anyOf", "oneOf", "allOf"):
        variants = schema.get(key)
        if variants:
            return " | ".join(_dedupe([_ts_type(variant) for variant in variants]))

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_dedupe([_ts_type({"type": item}) for item in schema_type]))

    if schema_type == "null":
        return "null"
    if schema_type == "string":
        return "string"
    if schema_type == "integer" or schema_type == "number":
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        item_type = _ts_type(schema.get("items", {}))
        if " | " in item_type:
            item_type = f"({item_type})"
        return f"{item_type}[]"
    if schema_type == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {_ts_type(additional)}>"
        if additional is True:
            return "Record<string, unknown>"

        properties = schema.get("properties")
        if isinstance(properties, dict) and properties:
            required = set(schema.get("required", []))
            fields = [
                f"{_prop(name)}{'?' if name not in required else ''}: {_ts_type(prop_schema)}"
                for name, prop_schema in properties.items()
            ]
            return "{ " + "; ".join(fields) + " }"

        return "Record<string, unknown>"

    return "unknown"


def _interface(name: str, schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for prop_name, prop_schema in schema.get("properties", {}).items():
        optional = "?" if prop_name not in required else ""
        lines.append(f"  {_prop(prop_name)}{optional}: {_ts_type(prop_schema)};")
    lines.append("}")
    return "\n".join(lines)


def _declaration(name: str, schema: dict[str, Any]) -> str:
    if schema.get("type") == "object" and schema.get("properties"):
        return _interface(name, schema)
    return f"export type {name} = {_ts_type(schema)};"


def generate() -> str:
    schemas = app.openapi().get("components", {}).get("schemas", {})
    declarations = [_declaration(name, schema) for name, schema in schemas.items()]
    return "\n\n".join(
        [
            "/* eslint-disable */",
            "// Generated by packages/types/scripts/openapi_to_ts.py.",
            "// Source of truth: services/api/app/schemas/*.py via FastAPI OpenAPI.",
            *declarations,
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(), encoding="utf-8")


if __name__ == "__main__":
    main()
